version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
